### ISSUE TITLE
report 1

### ISSUE THREAD

**Issue by rolandotr** [tahti/ADTool2#1]
ADTool 2.0 is still buggy and does not offer the same functionality than ADTool 1.0. Next I provide a bug report plus a list of features that are either missing or interesting to have.

- open in .adt format is not allowed, while it should be
- zoom in - zoom out cannot be done with the mouse, while does not fully work with key shortcuts
- In addition to the label, it would be nice to annotate nodes with comments
- control+Z functionality should be added

**Comment by mfraile** [comment]
Great tool people! We detected in ADTool 2.0 other features don't work or are missing:

- Space shortcut "fold below"
- Save an ADT file

Thanks!

**Comment by tahti** [comment]
Current version af ADTool solves the mentioned problems except for saving the ADT file. Saving of ADT files is not planned as the format was not very flexible and Java (de)serialization (used in ADT files) is a potential security issue.
