### ISSUE TITLE
ADTool 2.1.1 - Move the attack tree with the mouse

### ISSUE THREAD

**Issue by mfraile** [tahti/ADTool2#3]
Good morning,

Dear ADtool team,

The last version is working great, just one observation when you import an XML file at the beginning and you try to move the attack tree to the lef side with the mouse or cursor keys, the actions do not correspond, first, you must to zoom in the image, and then use the mouse or cursor for move properly the attack tree.

kind regards,

Marlon Fraile

**Comment by tahti** [comment]
This issue is solved in version 2.2.0 of ADTool.
